apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: cmp-plugin
spec:
  version: v1.0
  init:
    command: [sh, -c, 'echo "Initializing..."']
  generate:
    command: ["/bin/sops-parser"]
  discover:
    find:
      command: [/bin/discover]
